"""
Django settings for HidroComp_TCC project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

EXPORTDB = False
APP_NAME = 'odm2admin'
VERBOSE_NAME = "ODM2 Admin"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c9)=b5(07+xx*45-a&prz4qcvbt&&+pwc6=%xd!xrl8@6a$0*k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.gis',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #ODM2Admin
    'odm2admin',
    'ajax_select',
    'jquery',
    'djangocms_admin_style',
    'import_export',
    'social_django',
    'admin_shortcuts',
    'daterange_filter',
    'captcha',
    'fixture_magic',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HidroComp_TCC.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'HidroComp_TCC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'odm2',
        'USER': 'clebson',
        'PASSWORD': '89635241',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=public,admin,odm2,odm2extra'
        }
    }
}

"""################Configurações odm2admin################"""

""" SENSOR DASHBOARD CONFIGURATION """
SENSOR_DASHBOARD = {
    "time_series_days": 30,
    "featureactionids": [1699, 1784,1782,1701],
}
""" END SENSOR DASHBOARD CONFIGURATION"""

""" MAP CONFIGURATION """
MAP_CONFIG = {
    "lat": 0,
    "lon": 0,
    "zoom": 2,
    "cluster_feature_types": ['Profile','Specimen','Excavation','Field area'],
    "time_series_months": 1,
    "display_titles": True,
    "MapBox": {
      "access_token": 'mapbox accessToken'
    },
    "result_value_processing_levels_to_display": [1, 2, 3],
    "feature_types": ['Site','Profile','Specimen','Excavation','Field area',
                  'Weather station','Observation well','Stream gage','Transect']
}
""" END MAP CONFIGURATION """

""" SAMPLING FEATURE TYPE LEGEND MAPPING """
LEGEND_MAP = {
        'Excavation': dict(feature_type="Excavation", icon="fa-spoon", color="darkred",
                           style_class="awesome-marker-icon-darkred"),
        'Field area': dict(feature_type="Field area", icon="fa-map-o", color="darkblue",
                           style_class="awesome-marker-icon-darkblue"),
        'Weather station': dict(feature_type="Weather station", icon="fa-cloud", color="darkblue",
                                style_class="awesome-marker-icon-darkblue"),
        'Ecological land classification': dict(feature_type="Ecological land classification",
                                               icon="fa-bar-chart", color="darkpurple",
                                               style_class="awesome-marker-icon-darkpurple"),
        'Observation well': dict(feature_type="Observation well", icon="fa-eye", color="orange",
                                 style_class="awesome-marker-icon-orange"),
        'Site': dict(feature_type="Site", icon="fa-dot-circle-o", color="green",
                     style_class="awesome-marker-icon-green"),
        'Stream gage': dict(feature_type="Stream gage", icon="fa-tint", color="blue",
                            style_class="awesome-marker-icon-blue"),
        'Transect': dict(feature_type="Transect", icon="fa-area-chart", color="cadetblue",
                         style_class="awesome-marker-icon-cadetblue"),
        'Profile': dict(feature_type="Profile", icon="fa-database", color="purple",
             style_class="awesome-marker-icon-purple"),
        'Specimen': dict(feature_type="Specimen", icon="fa-flask", color="cadetblue",
                         style_class="awesome-marker-icon-cadetblue")
    }
""" END SAMPLING FEATURE TYPE LEGEND MAPPING """

""" DATA DISCLAIMER CONFIGURATION """
DATA_DISCLAIMER = {
    "text" : "Add a link discribing where your data come from",
    "linktext" : "The name of my site",
    "link" : "http://mysiteswegpage.page/",
}
""" END DATA DISCLAIMER CONFIGURATION """

SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'social_core.pipeline.social_auth.associate_by_email',)


""" SAMPLING FEATURE TYPE LEGEND MAPPING """
LEGEND_MAP = {
        'Excavation': dict(feature_type="Excavation", icon="fa-spoon", color="darkred",
                           style_class="awesome-marker-icon-darkred"),
        'Field area': dict(feature_type="Field area", icon="fa-map-o", color="darkblue",
                           style_class="awesome-marker-icon-darkblue"),
        'Weather station': dict(feature_type="Weather station", icon="fa-cloud", color="darkblue",
                                style_class="awesome-marker-icon-darkblue"),
        'Ecological land classification': dict(feature_type="Ecological land classification",
                                               icon="fa-bar-chart", color="darkpurple",
                                               style_class="awesome-marker-icon-darkpurple"),
        'Observation well': dict(feature_type="Observation well", icon="fa-eye", color="orange",
                                 style_class="awesome-marker-icon-orange"),
        'Site': dict(feature_type="Site", icon="fa-dot-circle-o", color="green",
                     style_class="awesome-marker-icon-green"),
        'Stream gage': dict(feature_type="Stream gage", icon="fa-tint", color="blue",
                            style_class="awesome-marker-icon-blue"),
        'Transect': dict(feature_type="Transect", icon="fa-area-chart", color="cadetblue",
                         style_class="awesome-marker-icon-cadetblue"),
        'Profile': dict(feature_type="Profile", icon="fa-database", color="purple",
             style_class="awesome-marker-icon-purple"),
        'Specimen': dict(feature_type="Specimen", icon="fa-flask", color="cadetblue",
                         style_class="awesome-marker-icon-cadetblue")
    }
""" END SAMPLING FEATURE TYPE LEGEND MAPPING """

"""################Configurações odm2admin################"""
# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
